export default [
  {
    login: "mnai01",
    id: 44310933,
    node_id: "MDQ6VXNlcjQ0MzEwOTMz",
    avatar_url: "https://avatars.githubusercontent.com/u/44310933?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mnai01",
    html_url: "https://github.com/mnai01",
    followers_url: "https://api.github.com/users/mnai01/followers",
    following_url: "https://api.github.com/users/mnai01/following{/other_user}",
    gists_url: "https://api.github.com/users/mnai01/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mnai01/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mnai01/subscriptions",
    organizations_url: "https://api.github.com/users/mnai01/orgs",
    repos_url: "https://api.github.com/users/mnai01/repos",
    events_url: "https://api.github.com/users/mnai01/events{/privacy}",
    received_events_url: "https://api.github.com/users/mnai01/received_events",
    type: "User",
    site_admin: false,
  },
];
