export default {
  login: "Thiratikan",
  id: 91763397,
  node_id: "U_kgDOBXgyxQ",
  avatar_url: "https://avatars.githubusercontent.com/u/91763397?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Thiratikan",
  html_url: "https://github.com/Thiratikan",
  followers_url: "https://api.github.com/users/Thiratikan/followers",
  following_url:
    "https://api.github.com/users/Thiratikan/following{/other_user}",
  gists_url: "https://api.github.com/users/Thiratikan/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Thiratikan/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Thiratikan/subscriptions",
  organizations_url: "https://api.github.com/users/Thiratikan/orgs",
  repos_url: "https://api.github.com/users/Thiratikan/repos",
  events_url: "https://api.github.com/users/Thiratikan/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Thiratikan/received_events",
  type: "User",
  site_admin: false,
  name: "Thiratikan",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 6,
  public_gists: 0,
  followers: 1,
  following: 2,
  created_at: "2021-10-01T22:43:06Z",
  updated_at: "2022-09-27T03:56:32Z",
};
